### PR TITLE
[feat ]List tree

### PR DESCRIPTION
**Pull request by takuyahirata23**

### CODE REVIEW

**Comment by MikeIbberson** [comment]
I made a small stylistic change, but there's a bit of refactoring I'll let you do here:

1. Archer, Legend, and Tree all check for array length before rendering the list components. Maybe, let's write an HOC to handle that logic? If not array or length, then we can handle all components in the same way.

2. Legend and Element both use addLeadingZero and both increment the array index by 1 when invoking it. Since that's the standard implementation, let's make it so that addLeadingZero handles the + 1 and we just pass the value to it directly. That will get rid of some redundancy.

**Comment by MikeIbberson** [comment]
Thanks for doing these refactorings! Unfortunately, I have a few more small comments :(

First, your HOC test case is good but it might be worth refactoring your assertions. Whenever you repeat yourself, such as three lines of .toBeNull(), there's probably a cleaner way of doing it. In this case, you could iterate through [case1, case2, case3] and invoke getElement() on each.

Second, while I do like functional programming, I think in this particular case it adds more complexity than is probably necessary. If we keep it, then let's delete the other helper function so there's only one. Before we do that, though, is there a way to make it more readable? There's just a high technical barrier to understand what exactly it's doing.

**Comment by takuyahirata23** [comment]
> Thanks for doing these refactorings! Unfortunately, I have a few more small comments :(
> 
> First, your HOC test case is good but it might be worth refactoring your assertions. Whenever you repeat yourself, such as three lines of .toBeNull(), there's probably a cleaner way of doing it. In this case, you could iterate through [case1, case2, case3] and invoke getElement() on each.
> 
> Second, while I do like functional programming, I think in this particular case it adds more complexity than is probably necessary. If we keep it, then let's delete the other helper function so there's only one. Before we do that, though, is there a way to make it more readable? There's just a high technical barrier to understand what exactly it's doing.

Thanks for reviewing my code! I'm happy to change thee assertions.

I personally thought it's readable because less variables, and each functions do one thing. Having said that, I agree that there is unnecessary complexity and too many functions for one task. Let's increment 1 in addLeadingZero so we only need one function. I'll refactor it over this weekend. Thanks for the review again. I really appreciate it :) I do feel I'm becoming a better developer!

**Comment by takuyahirata23** [comment]
I refactored addLeadingZero and test assertions! Let me know further refactoring is needed :)

**Comment by MikeIbberson** [comment]
This is perfect :) If we wanted to go to the extreme here, we could convert the statement "const leading = i + 1;" into another function (i.e. incrementer or something along those lines) but since we're dealing with such a small block of code, it'd be overkill IMO. So I'll merge this in now!

**Pull request merged**
