### PR TITLE
[chore] Footer/Estate

### PR DESCRIPTION
**Pull request by takuyahirata23**

### CODE REVIEW

**Comment by MikeIbberson** [comment]
Alrighty, I've done some review here and there are a couple of areas we can focus on to get this across the finish line.

1. I'd recommend taking the makeStyles function out of the component. Ideally, you want functions to be somewhat single purpose, so it's best to re-locate that block and just implement it in the component instead. Sometimes, I'll even make a file just for useStyle in the component folder. On this note, I've also just committed a small change to show how we can use the theme props for controlling the colour of the footer. This link might help: https://material-ui.com/customization/default-theme/

2. DigitalProperties uses SocialIcon in the same way as Grocery. Let's look at abstracting that so we can use it again in other footer components down the line.

3. Like you did with the company prop, let's replace "Privacy Policy" with a variable so that we can dynamically link to policy pages in implementation.

4. The components need some padding/margin. Perhaps look at the MUI Container component to help with that or use the p property on Box.

**Comment by MikeIbberson** [comment]
Sorry, one more item. For the Storybook configuration, can you rename all Footer stories so that they have the title in the sidebar? Might help with organization as opposed to having them under "other".

**Comment by takuyahirata23** [comment]
> Sorry, one more item. For the Storybook configuration, can you rename all Footer stories so that they have the title in the sidebar? Might help with organization as opposed to having them under "other".

Stories like WithColumns and EasteFooter are under the Footer menu. Do you want them to be parents instead of children?

**Comment by MikeIbberson** [comment]
> > Sorry, one more item. For the Storybook configuration, can you rename all Footer stories so that they have the title in the sidebar? Might help with organization as opposed to having them under "other".
> 
> Stories like WithColumns and EasteFooter are under the Footer menu. Do you want them to be parents instead of children?

Yup, we should have it match the way Layouts and Navigation looks. Right now, footers is under "Other" but it should really be it's own section in the menu.

image

**Pull request merged**
